import Product from '../models/Product.js';
import User from '../models/User.js';

const sampleProducts = [
  {
    name: 'Nike Air Force 1 07',
    description: 'A timeless all-white icon with crisp leather panels and everyday comfort.',
    price: 1999,
    discountPrice: 1749,
    countInStock: 14,
    sku: 'NAF1-07-001',
    category: 'Lifestyle',
    brand: 'Nike',
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['White'],
    collections: 'all',
    material: 'Leather',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/nike-air-force-1-07.jpg', altText: 'Nike Air Force 1 07' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.8,
    numReviews: 42,
    tags: ['classic', 'everyday', 'low-top'],
  },
  {
    name: 'Nike Dunk Low Panda',
    description: 'Clean black and white blocking made for rotation-friendly daily wear.',
    price: 1699,
    discountPrice: 1499,
    countInStock: 12,
    sku: 'NDL-PANDA-002',
    category: 'Lifestyle',
    brand: 'Nike',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Black', 'White'],
    collections: 'all',
    material: 'Leather',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/nike-dunk-low-panda.jpg', altText: 'Nike Dunk Low Panda' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.7,
    numReviews: 31,
    tags: ['streetwear', 'low-top'],
  },
  {
    name: 'Air Jordan 1 Retro High OG',
    description: 'The legendary high-top silhouette that bridges basketball heritage and culture.',
    price: 2399,
    discountPrice: 2099,
    countInStock: 10,
    sku: 'AJ1-HIGH-003',
    category: 'Basketball',
    brand: 'Jordan',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Red', 'Black', 'White'],
    collections: 'featured',
    material: 'Leather',
    gender: 'Men',
    images: [{ url: '/images/sneakers/air-jordan-1-retro-high-og.jpg', altText: 'Air Jordan 1 Retro High OG' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.9,
    numReviews: 38,
    tags: ['basketball', 'retro', 'iconic'],
  },
  {
    name: 'Air Jordan 4 Retro',
    description: 'Bold paneling, visible Air, and premium cushioning on a fan-favorite retro model.',
    price: 2899,
    discountPrice: 2599,
    countInStock: 7,
    sku: 'AJ4-RETRO-004',
    category: 'Basketball',
    brand: 'Jordan',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Grey'],
    collections: 'featured',
    material: 'Leather',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/air-jordan-4-retro.jpg', altText: 'Air Jordan 4 Retro' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.9,
    numReviews: 28,
    tags: ['retro', 'basketball'],
  },
  {
    name: 'Adidas Samba OG',
    description: 'A terrace classic with smooth leather, suede overlays, and gum sole heritage.',
    price: 1799,
    discountPrice: 1599,
    countInStock: 16,
    sku: 'ASAMBA-OG-005',
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White', 'Black'],
    collections: 'all',
    material: 'Leather',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/adidas-samba-og.jpg', altText: 'Adidas Samba OG' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.6,
    numReviews: 25,
    tags: ['terrace', 'classic'],
  },
  {
    name: 'Adidas Yeezy Boost 350 V2',
    description: 'A knit upper and responsive cushioning for a minimalist premium look.',
    price: 3499,
    discountPrice: 3199,
    countInStock: 5,
    sku: 'AY350-V2-006',
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Core Black', 'Slate'],
    collections: 'new',
    material: 'Knit',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/adidas-yeezy-boost-350-v2.jpg', altText: 'Adidas Yeezy Boost 350 V2' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.8,
    numReviews: 22,
    tags: ['premium', 'knit'],
  },
  {
    name: 'Adidas UltraBoost 1.0',
    description: 'High-energy return and a breathable knit upper built for long runs.',
    price: 3099,
    discountPrice: 2799,
    countInStock: 9,
    sku: 'AUB-10-007',
    category: 'Running',
    brand: 'Adidas',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White'],
    collections: 'featured',
    material: 'Knit',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/adidas-ultraboost-1-0.jpg', altText: 'Adidas UltraBoost 1.0' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.7,
    numReviews: 19,
    tags: ['running', 'comfort'],
  },
  {
    name: 'New Balance 550',
    description: 'Retro hoops DNA transformed into a modern everyday streetwear staple.',
    price: 2199,
    discountPrice: 1899,
    countInStock: 11,
    sku: 'NB-550-008',
    category: 'Lifestyle',
    brand: 'New Balance',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White', 'Green'],
    collections: 'all',
    material: 'Leather',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/new-balance-550.jpg', altText: 'New Balance 550' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.6,
    numReviews: 17,
    tags: ['retro', 'basketball'],
  },
  {
    name: 'New Balance 2002R',
    description: 'Suede and mesh layering with cushioned comfort for all-day wear.',
    price: 2599,
    discountPrice: 2299,
    countInStock: 8,
    sku: 'NB-2002R-009',
    category: 'Lifestyle',
    brand: 'New Balance',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Grey', 'Navy'],
    collections: 'new',
    material: 'Mesh',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/new-balance-2002r.jpg', altText: 'New Balance 2002R' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.8,
    numReviews: 16,
    tags: ['comfort', 'runner-inspired'],
  },
  {
    name: 'Asics GEL 1130',
    description: 'Early-2000s running aesthetic with breathable comfort and support.',
    price: 2099,
    discountPrice: 1849,
    countInStock: 10,
    sku: 'AS-1130-010',
    category: 'Running',
    brand: 'Asics',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Silver', 'White'],
    collections: 'all',
    material: 'Mesh',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/asics-gel-1130.jpg', altText: 'Asics GEL 1130' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.5,
    numReviews: 14,
    tags: ['running', 'retro-runner'],
  },
  {
    name: 'Asics GEL Kayano 30',
    description: 'Stability-focused running shoe with modern cushioning and smooth transitions.',
    price: 2899,
    discountPrice: 2599,
    countInStock: 9,
    sku: 'ASK-30-011',
    category: 'Running',
    brand: 'Asics',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Blue', 'Black'],
    collections: 'featured',
    material: 'Mesh',
    gender: 'Men',
    images: [{ url: '/images/sneakers/asics-gel-kayano-30.jpg', altText: 'Asics GEL Kayano 30' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.7,
    numReviews: 13,
    tags: ['support', 'long-distance'],
  },
  {
    name: 'Puma Suede Classic XXI',
    description: 'A true classic with rich suede texture and easy everyday styling.',
    price: 1499,
    discountPrice: 1299,
    countInStock: 13,
    sku: 'PSC-XXI-012',
    category: 'Lifestyle',
    brand: 'Puma',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Black', 'White'],
    collections: 'all',
    material: 'Suede',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/puma-suede-classic-xxi.jpg', altText: 'Puma Suede Classic XXI' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.4,
    numReviews: 11,
    tags: ['classic', 'suede'],
  },
  {
    name: 'Converse Chuck 70 High',
    description: 'Vintage-inspired high-top with premium canvas and enhanced cushioning.',
    price: 1399,
    discountPrice: 1199,
    countInStock: 15,
    sku: 'CCH70-013',
    category: 'Lifestyle',
    brand: 'Converse',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Black', 'White'],
    collections: 'all',
    material: 'Canvas',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/converse-chuck-70-high.jpg', altText: 'Converse Chuck 70 High' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.5,
    numReviews: 21,
    tags: ['canvas', 'high-top'],
  },
  {
    name: 'Vans Old Skool Classic',
    description: 'Iconic side-stripe skate silhouette with durable suede-canvas construction.',
    price: 1299,
    discountPrice: 1099,
    countInStock: 15,
    sku: 'VOS-014',
    category: 'Skateboarding',
    brand: 'Vans',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Black', 'White'],
    collections: 'all',
    material: 'Canvas',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/vans-old-skool-classic.jpg', altText: 'Vans Old Skool Classic' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.4,
    numReviews: 18,
    tags: ['skate', 'classic'],
  },
  {
    name: 'Nike Air Max 270',
    description: 'Large-volume Air cushioning with a sleek look built for everyday movement.',
    price: 2399,
    discountPrice: 2099,
    countInStock: 9,
    sku: 'NAM270-015',
    category: 'Lifestyle',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Blue'],
    collections: 'featured',
    material: 'Mesh',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/nike-air-max-270.jpg', altText: 'Nike Air Max 270' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.7,
    numReviews: 27,
    tags: ['air', 'streetwear'],
  },
  {
    name: 'Air Jordan 3 Retro White Cement',
    description: 'A legendary mid-cut retro with elephant print details and classic Jordan DNA.',
    price: 2999,
    discountPrice: 2699,
    countInStock: 8,
    sku: 'AJ3-WC-016',
    category: 'Basketball',
    brand: 'Jordan',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['White', 'Grey', 'Black'],
    collections: 'featured',
    material: 'Leather',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/air-jordan-3-retro-white-cement.jpg', altText: 'Air Jordan 3 Retro White Cement' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.8,
    numReviews: 19,
    tags: ['retro', 'basketball', 'iconic'],
  },
  {
    name: 'Nike Kobe 6 Protro Grinch',
    description: 'Low-profile performance basketball sneaker with aggressive traction and iconic colorway.',
    price: 3799,
    discountPrice: 3499,
    countInStock: 5,
    sku: 'NK6-GRINCH-017',
    category: 'Basketball',
    brand: 'Nike',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Green', 'Red', 'Black'],
    collections: 'new',
    material: 'Synthetic',
    gender: 'Men',
    images: [{ url: '/images/sneakers/nike-kobe-6-protro-grinch.jpg', altText: 'Nike Kobe 6 Protro Grinch' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.9,
    numReviews: 14,
    tags: ['basketball', 'performance', 'limited'],
  },
  {
    name: 'Adidas Campus 00s',
    description: 'Chunky skate-inspired reinterpretation of the classic Campus silhouette.',
    price: 1899,
    discountPrice: 1649,
    countInStock: 12,
    sku: 'ADC-00S-018',
    category: 'Lifestyle',
    brand: 'Adidas',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Grey', 'White'],
    collections: 'all',
    material: 'Suede',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/adidas-campus-00s.jpg', altText: 'Adidas Campus 00s' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.6,
    numReviews: 12,
    tags: ['casual', 'skate-inspired'],
  },
  {
    name: 'New Balance 9060',
    description: 'Futuristic blend of heritage runner cues and modern chunky tooling.',
    price: 2799,
    discountPrice: 2499,
    countInStock: 9,
    sku: 'NB-9060-019',
    category: 'Lifestyle',
    brand: 'New Balance',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Grey', 'Cream'],
    collections: 'new',
    material: 'Mesh',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/new-balance-9060.jpg', altText: 'New Balance 9060' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.7,
    numReviews: 10,
    tags: ['chunky', 'modern'],
  },
  {
    name: 'Asics GEL NYC',
    description: 'Retro running style with layered panels and cushioned GEL comfort.',
    price: 2499,
    discountPrice: 2199,
    countInStock: 9,
    sku: 'AS-GEL-NYC-020',
    category: 'Running',
    brand: 'Asics',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Silver', 'Blue'],
    collections: 'featured',
    material: 'Mesh',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/asics-gel-nyc.jpg', altText: 'Asics GEL NYC' }],
    isFeatured: true,
    isPublished: true,
    rating: 4.6,
    numReviews: 9,
    tags: ['retro-runner', 'comfort'],
  },
  {
    name: 'Puma Palermo',
    description: 'Terrace-style low-top with sleek proportions and vintage football energy.',
    price: 1699,
    discountPrice: 1499,
    countInStock: 11,
    sku: 'PUMA-PALERMO-021',
    category: 'Lifestyle',
    brand: 'Puma',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Green', 'White'],
    collections: 'all',
    material: 'Suede',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/puma-palermo.jpg', altText: 'Puma Palermo' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.5,
    numReviews: 8,
    tags: ['terrace', 'low-top'],
  },
  {
    name: 'Reebok Club C 85 Vintage',
    description: 'Minimal tennis-inspired sneaker with retro leather construction.',
    price: 1599,
    discountPrice: 1399,
    countInStock: 13,
    sku: 'RB-CLUBC85-022',
    category: 'Lifestyle',
    brand: 'Reebok',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White', 'Green'],
    collections: 'all',
    material: 'Leather',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/reebok-club-c-85-vintage.jpg', altText: 'Reebok Club C 85 Vintage' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.4,
    numReviews: 11,
    tags: ['tennis', 'vintage'],
  },
  {
    name: 'Saucony Shadow 6000',
    description: 'Heritage runner known for premium materials and everyday comfort.',
    price: 2199,
    discountPrice: 1949,
    countInStock: 8,
    sku: 'SAU-SHADOW-023',
    category: 'Running',
    brand: 'Saucony',
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Navy', 'Grey'],
    collections: 'new',
    material: 'Mesh',
    gender: 'Unisex',
    images: [{ url: '/images/sneakers/saucony-shadow-6000.jpg', altText: 'Saucony Shadow 6000' }],
    isFeatured: false,
    isPublished: true,
    rating: 4.5,
    numReviews: 7,
    tags: ['heritage', 'runner'],
  },
];

export const seedSampleProducts = async ({ reset = false } = {}) => {
  try {
    const existingCount = await Product.countDocuments();

    if (existingCount > 0 && !reset) {
      const products = await Product.find().sort({ createdAt: -1 }).limit(8);
      return { created: false, count: products.length, products };
    }

    if (reset) {
      await Product.deleteMany();
    }

    let adminUser = await User.findOne({ email: 'admin@example.com' });
    if (!adminUser) {
      adminUser = await User.create({
        name: 'Admin User',
        email: 'admin@example.com',
        password: '123456',
        role: 'admin',
      });
    }

    const productsToCreate = sampleProducts.map((product) => ({
      ...product,
      user: adminUser._id,
    }));

    const createdProducts = await Product.insertMany(productsToCreate);

    return { created: true, count: createdProducts.length, products: createdProducts };
  } catch (error) {
    console.error('Error seeding sample products:', error);
    throw error;
  }
};

export default seedSampleProducts;
